<wsdl:definitions xmlns:p0="urn:JSGX_MDM_MATERIALWsd/HTTPNone" xmlns:tns="urn:JSGX_MDM_MATERIALWsd" targetNamespace="urn:JSGX_MDM_MATERIALWsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"><UsingPolicy xmlns="http://schemas.xmlsoap.org/ws/2004/09/policy"/><wsdl:import location="file1.wsdl" namespace="urn:JSGX_MDM_MATERIALWsd/HTTPNone"/><wsdl:service name="JSGX_MDM_MATERIAL"><wsdl:port binding="p0:HTTPNoneBinding" name="HTTPNonePort"><soap:address location="http://jsgxpod.jsgx.net:50000/JSGX_MDM_MATERIAL/HTTPNone?style=document" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/></wsdl:port></wsdl:service></wsdl:definitions>