/**
 * JSGX_MDM_BUSINESS_PARTNERVi.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package JSGX_MDM_BUSINESS_PARTNERWsd;

public interface JSGX_MDM_BUSINESS_PARTNERVi extends java.rmi.Remote {
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.ApprovalStatusResultSet searchApprovalStatus(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.ApprovalStatusQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public beans.ws.mdm.sap.com.ExecutionStatus[] createBankAccount(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.BankAccountCreate[] bankAccount, beans.core.mdm.sap.com.RepositoryInformation reposInfo, beans.ws.mdm.sap.com.CreateConfigurationParameters configurationParameters) throws java.rmi.RemoteException;
    public beans.ws.mdm.sap.com.ExecutionStatus[] updateBankAccount(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.BankAccountUpdate[] bank_Account, beans.core.mdm.sap.com.RepositoryInformation reposInfo, beans.ws.mdm.sap.com.UpdateConfigurationParameters configurationParameters) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.BankAccountResultSet searchBankAccount(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.BankAccountQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public beans.ws.mdm.sap.com.ExecutionStatus[] createBanks(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.BanksCreate[] banks, beans.core.mdm.sap.com.RepositoryInformation reposInfo, beans.ws.mdm.sap.com.CreateConfigurationParameters configurationParameters) throws java.rmi.RemoteException;
    public beans.ws.mdm.sap.com.ExecutionStatus[] updateBanks(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.BanksUpdate[] banks, beans.core.mdm.sap.com.RepositoryInformation reposInfo, beans.ws.mdm.sap.com.UpdateConfigurationParameters configurationParameters) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.BanksResultSet searchBanks(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.BanksQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.BusinessSectionsResultSet searchBusinessSections(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.BusinessSectionsQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.ClientSystemsResultSet searchClientSystems(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.ClientSystemsQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CountriesResultSet searchCountries(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CountriesQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CurrencyResultSet searchCurrency(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CurrencyQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CustomerAccountGroupsResultSet searchCustomerAccountGroups(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CustomerAccountGroupsQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CustomerTypeResultSet searchCustomerType(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CustomerTypeQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public beans.ws.mdm.sap.com.ExecutionStatus[] createCustomers(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CustomersCreate[] customers, beans.core.mdm.sap.com.RepositoryInformation reposInfo, beans.ws.mdm.sap.com.CreateConfigurationParameters configurationParameters) throws java.rmi.RemoteException;
    public beans.ws.mdm.sap.com.ExecutionStatus[] updateCustomers(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CustomersUpdate[] customers, beans.core.mdm.sap.com.RepositoryInformation reposInfo, beans.ws.mdm.sap.com.UpdateConfigurationParameters configurationParameters) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CustomersResultSet searchCustomers(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.CustomersQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.DistributionStatusResultSet searchDistributionStatus(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.DistributionStatusQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.LanguagesResultSet searchLanguages(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.LanguagesQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.OperationResultSet searchOperation(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.OperationQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.OperationTypesResultSet searchOperationTypes(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.OperationTypesQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.RegionsResultSet searchRegions(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.RegionsQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.ServiceRelationshipsResultSet searchServiceRelationships(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.ServiceRelationshipsQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.TaxPayerKindsResultSet searchTaxPayerKinds(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.TaxPayerKindsQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.TitlesResultSet searchTitles(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.TitlesQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.TradePartnersResultSet searchTradePartners(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.TradePartnersQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.VendorAccountGroupsResultSet searchVendorAccountGroups(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.VendorAccountGroupsQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
    public beans.ws.mdm.sap.com.ExecutionStatus[] createVendors(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.VendorsCreate[] vendors, beans.core.mdm.sap.com.RepositoryInformation reposInfo, beans.ws.mdm.sap.com.CreateConfigurationParameters configurationParameters) throws java.rmi.RemoteException;
    public beans.ws.mdm.sap.com.ExecutionStatus[] updateVendors(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.VendorsUpdate[] vendors, beans.core.mdm.sap.com.RepositoryInformation reposInfo, beans.ws.mdm.sap.com.UpdateConfigurationParameters configurationParameters) throws java.rmi.RemoteException;
    public jsgx_mdm_business_partner.beans.ws.mdm.sap.com.VendorsResultSet searchVendors(jsgx_mdm_business_partner.beans.ws.mdm.sap.com.VendorsQuery query, beans.core.mdm.sap.com.RepositoryInformation reposInfo) throws java.rmi.RemoteException;
}
