<wsdl:definitions xmlns:p0="urn:FundcenterWsd/FundcenterBindingNS" xmlns:tns="urn:FundcenterWsd" targetNamespace="urn:FundcenterWsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"><UsingPolicy xmlns="http://schemas.xmlsoap.org/ws/2004/09/policy"/><wsdl:import location="file1.wsdl" namespace="urn:FundcenterWsd/FundcenterBindingNS"/><wsdl:service name="Fundcenter"><wsdl:port binding="p0:Fundcenter_FundcenterBinding" name="Fundcenter"><soap:address location="http://jsgxpod.jsgx.net:50000/sapws/sap.com/Fundcenter_ENTAPP_com.sap.mdm.ws.gen.ejbs_FundcenterVi/Fundcenter/Fundcenter?style=document" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/></wsdl:port></wsdl:service></wsdl:definitions>